CREATE TABLE IF NOT EXISTS orders (
	id BIGSERIAL PRIMARY KEY,
	user_id BIGINT NOT NULL REFERENCES users(id) ON DELETE CASCADE,
	number VARCHAR(255) NOT NULL UNIQUE,
	uploaded_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
	status VARCHAR(50),
	accrual REAL DEFAULT 0
);