CREATE TABLE users (
	id BIGSERIAL PRIMARY KEY,
	current REAL DEFAULT 0,
    withdrawn REAL DEFAULT 0
);

CREATE TABLE users_credentials (
	user_id BIGINT PRIMARY KEY REFERENCES users(id) ON DELETE CASCADE,
	login VARCHAR(128) NOT NULL UNIQUE,
	password VARCHAR(128) NOT NULL
);