CREATE TABLE withdrawals (
    id BIGINT PRIMARY KEY GENERATED ALWAYS AS IDENTITY,
    user_id BIGINT NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    number VARCHAR(255) NOT NULL UNIQUE,
    sum REAL NOT NULL CHECK (sum >= 0),
    processed_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);